# Generated by Django 5.1.4 on 2025-01-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsettag',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_set_tags', to='api.flashcardset'),
        ),
        migrations.AlterField(
            model_name='flashcardsettag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_flashcard_sets', to='api.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcardsettag',
            unique_together={('set', 'tag')},
        ),
    ]
