# Generated by Django 5.1.5 on 2025-01-27 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_password_hash_user_password_user_auth_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsetstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_set_stats_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcardstatssimple',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcardstatssimple', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcardsetfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_flashcard_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcardfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_flashcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcardstatspercent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcardstatspercent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcardstatsstages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcardstatsstages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
