services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flashcards_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200" #API HTTP
      - "9300:9300" #komunikacja wewnętrzna elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data

  flutter:
    build:
      context: ./src/gui/flutter
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    volumes:
      - ./src/gui/flutter:/app
    command: flutter run -d web-server

  logic:
    build:
      context: ./src/logic
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: flashcards.settings
    ports:
      - "8000:8000"
    volumes:
      - ./src/logic:/app
    command: python manage.py runserver 0.0.0.0:8000

  nexus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      NEXUS_ADMIN_PASSWORD: password123
    volumes:
      - nexus-data:/nexus-data


volumes:
  db_data:
  nexus-data:
  es_data:
