services:
  postgres-blue:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flashcards_db
    ports:
      - "56569:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  elasticsearch-blue:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password
      - ELASTIC_USERNAME=elastic
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "56560:9200" # API HTTP
      - "56561:9300" # Komunikacja wewnętrzna elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data

  minio-blue:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
    ports:
      - "56562:9000" # API HTTP
      - "56563:9001" # Konsola zarządzania
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  flutter-blue:
    build:
      context: ./src/gui/flutter
      dockerfile: Dockerfile
    ports:
      - "56568:8083"
    volumes:
      - ./src/gui/flutter:/app
    command: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=8083

  logic-blue:
    build:
      context: ./src/logic
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
    ports:
      - "56565:8000"
    volumes:
      - ./src/logic:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres-blue  # Zmieniono na postgres-blue

  migrate-blue:
    build:
      context: ./src/logic
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    depends_on:
      - postgres-blue  # Zmieniono na postgres-blue

  nexus-blue:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "56566:8081"
    environment:
      NEXUS_ADMIN_PASSWORD: password123
    volumes:
      - nexus-data:/nexus-data

volumes:
  db_data:
  nexus-data:
  es_data:
  minio_data:

