services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flashcards_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password
      - ELASTIC_USERNAME=elastic
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200" # API HTTP
      - "9300:9300" # Komunikacja wewnętrzna elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "user" 
      MINIO_ROOT_PASSWORD: "password" 
    ports:
      - "9000:9000" # API HTTP
      - "9001:9001" # Konsola zarządzania
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  flutter:
    build:
      context: ./src/gui/flutter
      dockerfile: Dockerfile_vm
    ports:
      - "8083:8083"
    volumes:
      - flutter_data:/app
    command: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=8083

  logic:
    build:
      context: ./src/logic
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      DJANGO_ENVIRONMENT: "green"  # Ustawienie środowiska "green"
    ports:
      - "8000:8000"
    volumes:
      - logic_data:/app
    command: sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

  migrate:
    build:
      context: ./src/logic
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    depends_on:
      - postgres

  nexus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      NEXUS_ADMIN_PASSWORD: password123
    volumes:
      - nexus-data:/nexus-data

volumes:
  db_data:
  nexus-data:
  es_data:
  minio_data:
  flutter_data:
  logic_data: